### PR TITLE
Fix warning by providing a architecture in the stage name of Dockerfile(s)

### LINKED ISSUE #53: `FromPlatformFlagConstDisallowed` warning
`FromPlatformFlagConstDisallowed: FROM --platform flag should not use constant value "linux/amd64"`

### PR DESCRIPTION
**Pull request by chrisvanrun**
Closes #53

### CODE REVIEW

**Review by jmsmkn — CHANGES_REQUESTED** [review]
In this case we want to force the platform as SageMaker **only** supports `linux/amd64`. Is there a way to suppress the warning instead? If not, both this and the "issue" can be closed.

**Comment by chrisvanrun** [comment]
> In this case we want to force the platform as SageMaker **only** supports `linux/amd64`. Is there a way to suppress the warning instead? If not, both this and the "issue" can be closed.

A quick check on the source:
- https://github.com/moby/buildkit/pull/5140

Suggests:
`...the stage name doesn't contain the OS or
architecture mentioned.`

**Comment by jmsmkn** [comment]
Also this is not redundant - this is done so that the builds work on arm/macos/windows machines without the user having to manually specify it each time they call docker build.

**Comment by chrisvanrun** [comment]
> Also this is not redundant - this is done so that the builds work on arm/macos/windows machines without the user having to manually specify it each time they call docker build.

It's redundant in the sense that the generated `test_run.sh` already has a build CLI arg to pick the platform. The Dockerfile addition is a nice safeguard if they decide to build via custom calls: so it's good to have.

**Review by jmsmkn — APPROVED** [review]

**Pull request merged**
